export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CATEGORY: "SET_CATEGORY",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_CART: 'SET_CART',
  COUNT_CART: 'COUNT_CART'
}